# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and test the solver 
        run: |
          nim c wordle_solver.nim
          testament r tests/wordle_solver/test_get_top_five_letters
          testament r tests/wordle_solver/test_get_words_containing_letters
          testament r tests/wordle_solver/test_update_word_list
          testament r tests/wordle_solver/test_all_words
          

